name: Feature request
description: Suggest an idea for SpessaSynth!
labels: [ "enhancement" ]
body:
  - type: markdown
    attributes:
      value: |
        Please note that this repository is for the web application *only.*
        Any suggestions for the audio playback / conversions should go to the [spessasynth_lib](https://github.com/spessasus/spessasynth_lib) repository.
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: Is your feature request related to a problem? Please describe.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Describe alternatives you've considered (if any)
  - type: textarea
    attributes:
      label: Additional info
      description: Any additional info and attachments (screenshots, MIDIs, soundfonts, other environments) go here.
    validations:
      required: false
