name: Feature request
description: Suggest an idea for SpessaSynth!
labels: [ "enhancement" ]
body:
  - type: dropdown
    id: scope
    attributes:
      label: Is your feature related to the sound library or the app/website?
      description: The library is responsible for making the sound and the website is what you see in the browser
      options:
        - spessasynth_lib
        - Web App/Local Edition
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: Is your feature request related to a problem? Please describe.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Describe alternatives you've considered (if any)
  - type: textarea
    attributes:
      label: Additional info
      description: Any additional info and attachments (screenshots, MIDIs, soundfonts, other environments) go here.
    validations:
      required: false
