name: Question
description: Something is unclear? Ask a question!
title: "[QUESTION] "
labels: [ "question" ]

body:
  - type: checkboxes
    attributes:
      label: Documentation confirmation
      options:
        - label: I confirm that I have read the documentation and have not found an answer there.
          required: true
  - type: textarea
    id: question
    attributes:
      label: Question
      description: Ask your question!
    validations:
      required: true